const express=require('express');const fs=require('fs');const path=require('path');const XLSX=require('xlsx');
const app=express();const PORT=process.env.PORT||10000;const DATA=path.join(__dirname,'data.json');const LIMIT=2000;
app.use(express.json({limit:'1mb'}));app.use(express.static(__dirname));
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch(e){return[]}}
function save(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2),'utf8')}
function now(){return new Date().toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})}
app.get('/api/submissions',(req,res)=>{const q=(req.query.q||'').trim();let d=load();if(q)d=d.filter(x=>(x.platoon+x.name).includes(q));res.json({limit:LIMIT,total:load().length,items:d.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))})});
app.post('/api/submit',(req,res)=>{let d=load();const b=req.body||{};if(!b.platoon||!b.name||!b.address||!b.bandPhone||!b.bank||!b.account||!b.accountHolder)return res.status(400).json({error:'모든 항목을 입력해주세요.'});let idx=d.findIndex(x=>x.platoon===b.platoon&&x.name===b.name);const t=now();if(idx>=0){d[idx]={...d[idx],...b,updatedAt:t,editCount:(d[idx].editCount||0)+1};save(d);return res.json({ok:true,mode:'updated',item:d[idx]})}if(d.length>=LIMIT)return res.status(400).json({error:`제출 가능 인원 ${LIMIT}명을 초과했습니다.`});const item={id:Date.now().toString(36),...b,createdAt:t,updatedAt:t,editCount:0};d.push(item);save(d);res.json({ok:true,mode:'created',item})});
app.delete('/api/submissions/:id',(req,res)=>{let d=load();d=d.filter(x=>x.id!==req.params.id);save(d);res.json({ok:true})});
app.get('/api/export',(req,res)=>{const d=load().map(x=>({'소대번호':x.platoon,'이름':x.name,'사복택배 주소':x.address,'BAND 전화번호':x.bandPhone,'은행':x.bank,'계좌번호':x.account,'예금주':x.accountHolder,'제출시간':x.createdAt,'최근수정':x.updatedAt,'수정횟수':x.editCount||0}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d),'제출현황');const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition','attachment; filename="navyform.xlsx"');res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.send(buf)});
app.listen(PORT,()=>console.log('Navyform server running on http://localhost:'+PORT));
