const express=require('express');const fs=require('fs');const path=require('path');const XLSX=require('xlsx');
const app=express();const PORT=process.env.PORT||10000;const DATA=path.join(__dirname,'data.json');const LIMIT=2000;const ADMIN_ID=process.env.ADMIN_ID||'기군단';const ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'2대대';
app.use(express.json({limit:'1mb'}));app.use(express.static(__dirname));
app.get('/admin',(req,res)=>res.sendFile(path.join(__dirname,'index.html')));

function initial(){return {activeCohort:'1기',cohorts:{'1기':[]}}}
function load(){try{const d=JSON.parse(fs.readFileSync(DATA,'utf8'));if(Array.isArray(d))return {activeCohort:'1기',cohorts:{'1기':d}};if(!d.cohorts||typeof d.cohorts!=='object')d.cohorts={};if(Object.keys(d.cohorts).length===0)d.cohorts['1기']=[];if(!d.activeCohort||!d.cohorts[d.activeCohort])d.activeCohort=Object.keys(d.cohorts)[0]||'1기';return d}catch(e){return initial()}}
function save(d){fs.writeFileSync(DATA,JSON.stringify(d,null,2),'utf8')}
function now(){return new Date().toLocaleString('ko-KR',{timeZone:'Asia/Seoul',hour12:false})}
function auth(req,res,next){const id=req.headers['x-admin-id']||req.query.adminId;const p=req.headers['x-admin-password']||req.query.password;if(id!==ADMIN_ID||p!==ADMIN_PASSWORD)return res.status(401).json({error:'관리자 아이디 또는 비밀번호가 올바르지 않습니다.'});next()}
app.post('/api/admin/login',(req,res)=>{const b=req.body||{};if(b.id===ADMIN_ID&&b.password===ADMIN_PASSWORD)return res.json({ok:true});return res.status(401).json({error:'관리자 아이디 또는 비밀번호가 올바르지 않습니다.'})})
function arr(d,cohort){const c=cohort||d.activeCohort;if(!d.cohorts[c])d.cohorts[c]=[];return d.cohorts[c]}
app.get('/api/status',(req,res)=>{const d=load();res.json({limit:LIMIT,activeCohort:d.activeCohort,cohorts:Object.keys(d.cohorts)})});
function setCohort(name,res){name=(name||'').trim();if(!name)return res.status(400).json({error:'기수를 입력해주세요.'});const d=load();if(!d.cohorts[name])d.cohorts[name]=[];d.activeCohort=name;save(d);res.json({ok:true,activeCohort:name,cohorts:Object.keys(d.cohorts)})}
app.post('/api/admin/cohort',auth,(req,res)=>setCohort(req.body.name,res));
app.get('/api/admin/create-cohort',auth,(req,res)=>setCohort(req.query.name,res));
app.get('/api/submissions',auth,(req,res)=>{const q=(req.query.q||'').trim();const d=load();const cohort=req.query.cohort||d.activeCohort;let items=[...arr(d,cohort)];if(q)items=items.filter(x=>((x.platoon||'')+(x.name||'')).includes(q));res.json({limit:LIMIT,activeCohort:d.activeCohort,cohort,total:arr(d,cohort).length,cohorts:Object.keys(d.cohorts),items:items.sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||''))})});
app.post('/api/submit',(req,res)=>{const d=load();const b=req.body||{};if(!b.platoon||!b.name||!b.address||!b.bandPhone||!b.bank||!b.account||!b.accountHolder)return res.status(400).json({error:'모든 항목을 입력해주세요.'});const items=arr(d,d.activeCohort);let idx=items.findIndex(x=>x.platoon===b.platoon&&x.name===b.name);const t=now();if(idx>=0){items[idx]={...items[idx],...b,cohort:d.activeCohort,updatedAt:t,editCount:(items[idx].editCount||0)+1};save(d);return res.json({ok:true,mode:'updated',item:items[idx],cohort:d.activeCohort})}if(items.length>=LIMIT)return res.status(400).json({error:`현재 기수 제출 가능 인원 ${LIMIT}명을 초과했습니다.`});const item={id:Date.now().toString(36),cohort:d.activeCohort,...b,createdAt:t,updatedAt:t,editCount:0};items.push(item);save(d);res.json({ok:true,mode:'created',item,cohort:d.activeCohort})});
app.delete('/api/submissions/:id',auth,(req,res)=>{const d=load();const cohort=req.query.cohort||d.activeCohort;d.cohorts[cohort]=arr(d,cohort).filter(x=>x.id!==req.params.id);save(d);res.json({ok:true})});
app.get('/api/export',auth,(req,res)=>{const d=load();const cohort=req.query.cohort||d.activeCohort;const rows=arr(d,cohort).map(x=>({'기수':cohort,'소대번호':x.platoon,'이름':x.name,'사복택배 주소':x.address,'BAND 전화번호':x.bandPhone,'은행':x.bank,'계좌번호':x.account,'예금주':x.accountHolder,'제출시간':x.createdAt,'최근수정':x.updatedAt,'수정횟수':x.editCount||0}));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),cohort);const buf=XLSX.write(wb,{type:'buffer',bookType:'xlsx'});res.setHeader('Content-Disposition',`attachment; filename="navyform_${encodeURIComponent(cohort)}.xlsx"`);res.setHeader('Content-Type','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.send(buf)});
app.listen(PORT,()=>console.log('Navyform server running on http://localhost:'+PORT));
